// .dockerignore
// .gitignore
// config.env
// Dockerfile
// index.html
// package-lock.json
// package.json
// README.md
// RestAPI.http
// server/
// ____controllers/
// ________|generalRule.js
// ________|lesson.js
// ________|notification/
// ____________|email.js
// ____________|whatsapp.js
// ________|room.js
// ________|session.js
// ________|student.js
// ________|subject.js
// ________|volunteer.js
// ____helpers/
// ________|connection.js
// ________|fileSystemPathes.js
// ________|helpersFunction.js
// ________|messages.js
// ________|populate.js
// ____middleware/
// ________|mongoose/
// ____________|delete.js
// ________|multer/
// ____________|lesson.js
// ____________|profileCover.js
// ____model/
// ________|model.js
// ____routes/
// ________|router.js
// server.js
// src/
// ____App.jsx
// ____assets/
// ____component/
// ________|adminbar.jsx
// ________|calendar.jsx
// ________|dashboardComponent/
// ____________|block1.jsx
// ____________|chart.jsx
// ____________|chart_component/
// ________________sessionChart.jsx
// ________________studentChart.jsx
// ________________volunteerChart.jsx
// ____________|dashboard.jsx
// ____________|notify.jsx
// ____________|popupComponent.jsx
// ____________|propabities.jsx
// ____________|session.jsx
// ____________|subjectCards.jsx
// ________|Demail.jsx
// ________|education.jsx
// ________|email.jsx
// ________|errorBoundary.jsx
// ________|form/
// ____________|lesson.jsx
// ____________|room.jsx
// ____________|session.jsx
// ____________|student.jsx
// ____________|subject.jsx
// ____________|subnav.jsx
// ____________|volunteer.jsx
// ________|home.jsx
// ________|include/
// ____________|noOfmember.jsx
// ____________|videohandler.jsx
// _____________imgUpload.jsx
// _____________input.jsx
// _____________select.jsx
// _____________textarea.jsx
// ________|lessonDetails.jsx
// ________|login.jsx
// ________|navbar.jsx
// ________|show/
// ____________|lessonTable.jsx
// ____________|profile.jsx
// ____________|roomTable.jsx
// ____________|sessionTable.jsx
// ____________|studentTable.jsx
// ____________|subjectTable.jsx
// ____________|volunteerTable.jsx
// ________|sidebar.jsx
// ________|users.jsx
// ________|whatsapp.jsx
// ____helpers/
// ________|apiEndpoints.js
// ________|backEndComments.js
// ________|crudFunctions.js
// ________|frontEndComments.js
// ________|helpersFunctions.js
// ________|messages.js
// ________|reactBasicFunc.js
// ____index.css
// ____index.jsx
// ____scss/
// ________|addvolunteer.scss
// ________|adminbar.scss
// ________|dashboard.scss
// ________|home.scss
// ________|lessonTable.scss
// ________|login.scss
// ________|navbar.scss
// ________|profile.scss
// ________|sessionTable.scss
// ________|sidebar.scss
// ________|subjectTable.scss
// ________|submitionForm.scss
// ________|test.scss
// ____testdesign.jsx
// ____viewPdf.jsx
// test.js
// uploads/
// ____lesson/
// ________|hi.txt
// ____profileCovers/
// ________|hi.txt
// vite.config.js
